### ISSUE TITLE
Document Format Errors

### ISSUE THREAD

**Issue by rmercer33** [rmercer33/christmind.info#11]
Edit this issue to report formatting errors.

Fixed | Source | Document | Error
--- | --- | --- | ---
N | Raj | 061415.md | One Omit was missing
y | Raj | 061415.md | 2nd to last paragraph: "what is the truth there?" should be "what is the truth here?"
n | " | " | [Raj did not read this sentence] was not {: .omit}'ed
y | " | 062115.md | <div tags do not include markdown="1"

**Comment by Julief8** [comment]
New issue, xxxx

**Comment by rmercer33** [comment]
close - we're not using this method of communicating formatting errors
