### ISSUE TITLE
Raj 2017 formatted md files 

### ISSUE THREAD

**Issue by Julief8** [rmercer33/christmind.info#118]
[Archive.zip](https://github.com/rmercer33/christmind.info/files/1627599/Archive.zip)

Not all of these were changed because a few had nothing to format but I included them all in this file.

Formatting Complete !!!!!  Yeah !!!

**Comment by rmercer33** [comment]
Good job!! Thank you. I'll try to get the changes published in the next hour or so...

**Comment by Julief8** [comment]
Great.  I’m getting close to finishing the timing on the first one, 040817 which actually was my 61st Birthday.  There are a few corrections to the md file from my timing it.

Cinta Banyak teman saya...
