### ISSUE TITLE
Raj082712-Sentence in wrong paragraph

### ISSUE THREAD

**Issue by Julief8** [rmercer33/christmind.info#20]
Remove from paragraph 10   "And you are frustrated with having to wait until you come around to the rings so that you might, perchance, have the brass ring next."

Move it to the bottom of the following paragraph. #11 

I didn't fix this in the md file because I didn't know if moving a whole sentence would screw up the timing.  I also stopped the timing at this point.  Please advise on this and also on what type of changes will screw up timing.  Thanks,  Julie

**Comment by rmercer33** [comment]
Okay, I see what you're talking about.

To continue the timing and make adjustments to the md file after the fact you have to pretend that the changes have already been made.

To remove the sentance from the first paragraph effectively shortens it and so the transition to the next paragraph needs to happen before that last sentance is spoken. That's where you click the bullseye.

Then, on the following paragraph you make the transition, click the bullseye, to the one after that after he speaks the sentance that will be moved to the end of that paragraph.

Wow, hope that makes sense. 

Take a stab at it if you want or I can make the changes and you can start the timing over again when it's ready.

**Comment by Julief8** [comment]
I thought that was the case and almost did it without asking. I will submit the corrected md file and finish the timing. Thanks

From Julie's iPhone

**Comment by Julief8** [comment]
Just finished the timing.  here is the corrected md file.  Cinta,  Jules
[082712.md.zip](https://github.com/rmercer33/christmind.info/files/1114115/082712.md.zip)

**Comment by rmercer33** [comment]
got it, thank you
